### ISSUE TITLE
Missing "Post Reply" button at the bottom 

### ISSUE THREAD

**Issue by Pocokk** [SubZeroPL/cs-rin-ru-enhanced-mod#14]
As you can see here https://cs.rin.ru/forum/viewtopic.php?f=14&t=75717, if I scroll down to the bottom with Infinite scrolling, I don't see the "Post Reply" button, I have to scroll up to the first page in order to create a new message.

![image](https://user-images.githubusercontent.com/81096046/158907680-a57c4a67-b7b9-452f-947d-c8a83aa5f75a.png)

**Comment by SubZeroPL** [comment]
Hi. Thanks for your report. There is already issue created for this: #2
