### ISSUE TITLE
Don't hide SCS by default

### ISSUE THREAD

**Issue by Helmasko** [SubZeroPL/cs-rin-ru-enhanced-mod#15]
I don't see the reason why only red SCS results are shown by default, shouldn't it be the opposite? I feel it just causes confusion for people. I think it should show either all except red, or should show all by default.

**Comment by SubZeroPL** [comment]
First thanks for your input :)
The way it works currently is just my personal preference. I wanted to only see SCS topic in unread posts list if it was not up to date ("red") so I'd know if I can upload something. By default this unread posts list is the only place that this function is in effect. You can also enable it in SCS section of the forum, but it's separate option in configuration and it's disabled by default. No filtering at all is done in search results (as that could be confusing).
The filtering in unread posts list (and by extension in SCS) is configurable in script settings (and of course can be disabled completely), but I've only added options I deemed necessary. This always can be extended, but as for now no one complained to me about it.
So I don't really see this as a bug, more like a enhancement request if you have idea how to handle it another way. I'll leave it open for now if you (or anyone else) have any more suggestions.

**Comment by Pocokk** [comment]
@SubZeroPL Dear SubZero,

Sorry to bother you and like this, but do you plan to continue make updates or start to clean-up the TODO list in the near future? Thank you in advance!

**Comment by SubZeroPL** [comment]
Yeah, I don't have much free time to work on the script, and for me it's working fine so I don't feel pressure to modify it. However if you have any suggestions for modifications or new features then you are welcome to create issue on Github (or comment on existing one), maybe this will motivate me to get to work ;)

**Comment by SubZeroPL** [comment]
closed in #19
