### ISSUE TITLE
How to install it ? (speaking French is possible)

### ISSUE THREAD

**Issue by ugoanas** [SubZeroPL/cs-rin-ru-enhanced-mod#16]
I don't understand what i need to do to install CS RIN RU Enhanced mod in Google Chrome.

Is someone can help me please ?

Thanks.

**Comment by SubZeroPL** [comment]
I don't speak French, sorry, but I'll try to explain as simple as possible. Two steps should be enough:
- instal [Violentmonkey](https://chrome.google.com/webstore/detail/violentmonkey/jinjaccalgkegednnccohejagnlnfdag)
- click on this link: https://raw.githubusercontent.com/SubZeroPL/cs-rin-ru-enhanced-mod/master/cs-rin-ru-enhanced-mod.user.js

And it should work

**Comment by ugoanas** [comment]
Thank you it works !

**Comment by ugoanas** [comment]
I just don't understand the difference between before and after.

**Comment by Altansar69** [comment]
google traduction n'est pas si mauvais ;)

**Comment by ugoanas** [comment]
je ne l'ai pas utilisé pour une phrase si courte et si simple !!

**Comment by Altansar69** [comment]
Je voulais parler de [SubZeroPL](https://github.com/SubZeroPL) ;)
