### ISSUE TITLE
Clicking on threads jump to a random page

### ISSUE THREAD

**Issue by Helmasko** [SubZeroPL/cs-rin-ru-enhanced-mod#23]
When clicking on any threads, every single time, it jumps to a random page on it. All my settings are at default.

**Comment by SubZeroPL** [comment]
In latest version by default the script changes topic links to lead to first unread post of this topic. You can change it in script configuration ("Change topic link" option).
Does it fix your problem?

**Comment by Altansar69** [comment]
@Helmasko Thank you for your feedback. SubZeroPL has been able to answer your question. 

I advise you to read the different options to choose what you want to enable or disable and personalise your experience as best you can.

On the other hand it's true that this option can lose people who keep the default options. The new update will therefore disable this option by default.

**Comment by Helmasko** [comment]
Thank you for the new update that seems to work. But it felt like a bug before since it used to jump to seemingly random pages on threads that I have never opened before. Not sure if this is an issue only on my end.

**Comment by Altansar69** [comment]
Well, I'm not sure. If we get any other feedback we'll try and have a look.

**Comment by Reddiepoint** [comment]
> But it felt like a bug before since it used to jump to seemingly random pages on threads that I have never opened before. Not sure if this is an issue only on my end.

I think this is more to do with the way cs.rin handles the position of unread posts.
