### ISSUE TITLE
Script don't work when you are not connected

### ISSUE THREAD

**Issue by Altansar69** [SubZeroPL/cs-rin-ru-enhanced-mod#25]
Some functions (I haven't tested them all) don't work if we're not connected to cs.rin.
We could test each function and adapt those that can to the case where we are not connected and put an error message to those being vital to be connected (the chat for example). 

But to be honest I think the easiest thing would be to just put an error message on absolutely every script saying that you need to be logged in for it to work. As this script is intended to improve the experience on the rin, the first improvement would be to create an account I think.

**Comment by SubZeroPL** [comment]
Honestly I never even tested this when not logged in as I'm logged in almost always. The easiest solution in my opinion would be to check in the beginning of the script if the user is logged in and disable the script (maybe with some information popup) if not.
What do you think?

**Comment by Altansar69** [comment]
I totally agree.
