### ISSUE TITLE
Infinite scrolling broken

### ISSUE THREAD

**Issue by SubZeroPL** [SubZeroPL/cs-rin-ru-enhanced-mod#29]
I think something broke down in infinite scrolling after last update.
Today when I wanted to check unread posts when I scrolled down first page the second page loaded fine but then when I scrolled down second page it loaded again and then it kept loading second page over and over again.
Also I don't remember how it worked before but when I scroll down to next page the page counter on the top of the page is behaving strange (like it shows page number that is not always correct).
Also I noticed that now I have to scroll the page to the bottom and then scroll again to load next one (but I assume this is intentional for it to work like scrolling up?)

I don't have too much time to test it more so for now I'm just creating this issue as a reminder.

**Comment by Reddiepoint** [comment]
Hmm... I didn't get this behaviour when I was testing it myself, nor can I seem to replicate this. What do your settings look like?

**Comment by SubZeroPL** [comment]
At the moment like this:

![obraz](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/45795042/1ca9d7f7-e3d8-4740-b607-c24241823d93)

**Comment by Reddiepoint** [comment]
I can confirm that with your settings, the bug does occur. I suspect it may have something to do with the `Hide SCS` option, as when I use your settings, but set it to `not hide` then the bug doesn't occur. Will need to do more testing to find a fix.
