### ISSUE TITLE
Topic title in unread posts list links directly to first unread post

### ISSUE THREAD

**Issue by SubZeroPL** [SubZeroPL/cs-rin-ru-enhanced-mod#3]

**Comment by Altansar69** [comment]
Meaning?
![image](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/97360807/d230b373-1e57-4427-81df-4c245c5f76e8)
for example, if I click on the topic title, it should go to the last page at the very bottom of the last post? Is that correct?

**Comment by SubZeroPL** [comment]
Yes, that's correct. I've seen this feature on some other forum software and liked it very much.

**Comment by Altansar69** [comment]
I make this for you ;)

**Comment by Altansar69** [comment]
the solution I proposed works in viewforum but not yet in search

**Comment by SubZeroPL** [comment]
No problem, take your time.
