### ISSUE TITLE
Color you your name

### ISSUE THREAD

**Issue by Altansar69** [SubZeroPL/cs-rin-ru-enhanced-mod#31]
Like color friend but for you

**Comment by Altansar69** [comment]
yeah, true. I finally just added it to "colour your friend".
Do you think we should do the combobox anyway?

**Comment by Reddiepoint** [comment]
It's up to you, I think it's fine without the combo box.

**Comment by Altansar69** [comment]
OK, I'll do it. I'll reopen the issue and do it when I have time.
