### ISSUE TITLE
Script won't work anymore

### ISSUE THREAD

**Issue by Altansar69** [SubZeroPL/cs-rin-ru-enhanced-mod#38]
https://cs.rin.ru/forum/viewtopic.php?p=2871397#p2871397

**Comment by Reddiepoint** [comment]
Do you know browser, script manager and version of the script he is using?

**Comment by Altansar69** [comment]
You already see it but he use firefox, tampermonkey and latest version.

**Comment by Reddiepoint** [comment]
Yeah, he replied a few days ago, but I'm still waiting for him to reply with information that will help us replicate his problem.
