### ISSUE TITLE
Separator between "pages" in infinite scrolling mode

### ISSUE THREAD

**Issue by SubZeroPL** [SubZeroPL/cs-rin-ru-enhanced-mod#4]

**Comment by Altansar69** [comment]
I'm willing to do it, but I don't have a separator idea. What should I put in the separator?

**Comment by Altansar69** [comment]
oh but you're talking for viewforum.php I thought you were talking for viewtopic

**Comment by Altansar69** [comment]
where would you like the separator to be? Only in viewforum or everywhere?

**Comment by SubZeroPL** [comment]
I think it would be nice to have it everywhere where infinite scrolling is available. The one for viewtopic can be just empty bar as it is now after first 'page'

**Comment by Reddiepoint** [comment]
Are you guys still interested in this idea, especially since the nav bar gets updated with the right page now?

**Comment by SubZeroPL** [comment]
What nav bar?

**Comment by Reddiepoint** [comment]
You know the bar in the top left with the page numbers?

**Comment by SubZeroPL** [comment]
Yeah, but it's only visible when you are on the top of the page and when I scroll back to top it always shows page 1 as active.
If I scroll to top of the page with keyboard (PageUp or Home key) then I assume it does not trigger scrolling functions and shows correct page.

**Comment by Reddiepoint** [comment]
That's odd, I tried to make it so that the nav bar is always visible when you scroll (it goes back to it's original place when you scroll back to where it originally is). If you scroll using the keyboard the nav bar won't be updated because it only updates on the `wheel` event.

**Comment by SubZeroPL** [comment]
This is how it looks for me:
[screen.webm](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/45795042/7bda250b-ccb0-4abc-9c35-58b5b8297f23)

**Comment by Altansar69** [comment]
It works for me personally, and it's very strange that it doesn't work for you.

**Comment by Reddiepoint** [comment]
This is what it's supposed to look like:
![msedge_7V4LaQOB3b](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/31847741/7dc19fd2-7be3-410e-a85e-e7f5d75a925f)

**Comment by SubZeroPL** [comment]
I'm using latest Firefox with Violentmonkey

**Comment by Altansar69** [comment]
Can you also send us a screenshot of the config? Perhaps some of the script's functionality is in conflict

**Comment by SubZeroPL** [comment]
At the moment like this:

![obraz](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/45795042/1ca9d7f7-e3d8-4740-b607-c24241823d93)

_Originally posted by @SubZeroPL in https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/issues/29#issuecomment-1638062225_

**Comment by SubZeroPL** [comment]
I think I've fixed it in #35

**Comment by SubZeroPL** [comment]
Closed as it's not really needed anymore
