### ISSUE TITLE
Mention issues

### ISSUE THREAD

**Issue by Altansar69** [SubZeroPL/cs-rin-ru-enhanced-mod#42]
Problem that affects people with spaces in their nickname (maybe also people with special characters, it's to be tested), in fact instead of putting the space when you click on the mention button it displays %20. Here's an example: https://cs.rin.ru/forum/posting.php?mode=reply&f=14&t=135809&do=mention&p=2912090&u=1880394&a=Fax%20machine

**Comment by Reddiepoint** [comment]
Perhaps something like [decodeURI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/decodeURI) might work for this.
