### ISSUE TITLE
on every game page of steam / steamdb game add button to go to the cs.rin topic

### ISSUE THREAD

**Issue by Altansar69** [SubZeroPL/cs-rin-ru-enhanced-mod#47]
Something like that:
```html
<a class="btnv6_blue_hoverfade btn_medium" href="https://cs.rin.ru/forum/viewtopic.php?f=10&amp;t=114113&amp;hilit=1248130&amp;sid=fe52883a4b83d458174b7668bacfdb2b"><span data-tooltip-text="View on cs.rin.ru"><img src="data:image/x-icon;base64,AAABAAEAEBAAAAEAIABoBAAAFgAAACgAAAAQAAAAIAAAAAEAIAAAAAAAAAQAABILAAASCwAAAAAAAAAAAAAeHh4EHh4eCB4eHgAeHh4AHh4eAB4eHgAeHh4iHh4ejB4eHiMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAHh4efB4eHqYeHh4BHh4eAB4eHgAeHh4AHh4ehB4eHuUeHh4PAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB4eHpIeHh7/Hh4emh4eHgAeHh4AHh4eAB4eHrgeHh63AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAeHh4PHh4euR4eHv8eHh4zHh4eAB4eHhIeHh7uExMv/wYGQf8FBTr/BQU6/wUFOf8FBTn/BQU6/wUFQP8GBkf/Hh4eAB4eHjQeHh7/Hh4egR4eHgAeHh5+Hh4e/w4OM/8GBiX/Bwca/wgIG/9WVl//FRUk/wcHG/8HByf/BwdB/x4eHgAeHh4IHh4e2x4eHtceHh5hHh4e/x4eHqIKCjr/EBAk/xMTE/89PT3/09PT/0VFRf8TExP/EBAk/woKPf8KCk3/Dg5M/xkZMv8eHh7/Hh4e/x4eHv8bGzn/MDBH/2pqcP/k5OT/srKy/21tbf/v7+//hoaG/yUlN/8QEEP/DAxN/zIyQv8rKzD/Hh4e/x4eHv8qKjL/UFBa/9PT0/+ZmZv/QEBA/zs7O/87Ozv/f39//9jY2P98fIT/FhZJ/xAQTv9FRVD/ODg4/x4eHv8eHh7/Pz8//1BQUP9WVlb/UFBQ/1BQUP9QUFD/UFBQ/1NTU/9wcHD/ODhM/x0dTv8SElH/V1dh/09PT/8eHh7/Hh4e/ysrK/8/Pz//WVlZ/1paWv9gYGD/ZGRk/2RkZP9kZGT/ZGRk/0ZGXP8jI1T/FBRT/2dncf9iYmL/Hh4e/x4eHv8eHh7/Hh4e/yAgIP8xMTP/U1Nf/0xMZP9MTGP/TExj/0xMZP84OF7/GxtU/xYWVP92doD/hoaG/0FBQf8eHh7/IyMj/ycnJ/8gICD/JSUm/y8vO/8vL1L/Nzdg/zQ0Yf8zM2H/JiZb/xcXU/8XF1b/hoaP/5mZmf+Li4v/JSUl/yYmJv96enr/ioqK/2pqff86OmL/Hh4eDBMTWQATE1n/ExNZ/wAAAAAAAAAAERFU/4eHlv+RkZr/jY2Y/1RUWv9LS1H/f3+P/35+j/9fX3//MTFk/xsbYQAbG2EAGxth/xsbYf8AAAAAAAAAAA4OUv8ZGVj/Jydg/ywsYv8xMWX/NTVo/zo6av8+Pm3/LS1k/yUlXv8bG2EAGxthABsbYf8bG2H/AAAAAAAAAAAbG2EAGxthABsbYQAbG2EAGxthABsbYQAbG2EAGxthABsbYQAbG2EAGxthABsbYQAbG2H/Gxth/wAAAAAAAAAAPH8AABx/AAAc/wAACAAAAIgAAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABMAAAAzAAAAMwAA//MAAA==">
</span></a>
```

for found the url of the cs.rin game page, make a request at this url:
https://cs.rin.ru/forum/search.php?keywords=1158310&terms=all&author=&sc=1&sf=firstpost&sk=t&sd=d&sr=topics&st=0&ch=300&t=0
(replace 1158310 by the appid)
and get the 1st link of the result
![image](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/97360807/7cfa2659-59f0-4a13-9d7b-d55d481f88e9)

**Comment by Altansar69** [comment]
![image](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/97360807/001ee896-a0c3-44ed-963b-42a6e5b6d119)
don't ask me why the ico look like that

**Comment by Reddiepoint** [comment]
I think you could modify the CS.RIN URL by specifying the forum ID to limit the number of posts to 1, like this https://cs.rin.ru/forum/search.php?keywords={AppID}&terms=all&author=&fid%5B%5D=10&sc=1&sf=firstpost&sk=t&sd=d&sr=topics&st=0&ch=300&t=0 (adding the **&fid%5B%5D=10** to the URL).

I think it would be quite useful to add a separate button for games in other places, for example, under genres/search or when you hover over a game and a preview pops up. This button won't link directly to a CS.RIN topic (to avoid spamming the forum) but it could have a HREF to the search URL. You could name this button "Quick search" or something more creative.

**Comment by SubZeroPL** [comment]
I don't think it's a good idea, this script is specifically for modifying cs.rin.ru page, and not other pages.

**Comment by Altansar69** [comment]
I create this repo: https://github.com/Altansar69/CS.RIN.RU-Enhanced-external
