### ISSUE TITLE
seach for all post by a specific user

### ISSUE THREAD

**Issue by Altansar69** [SubZeroPL/cs-rin-ru-enhanced-mod#49]
https://cs.rin.ru/forum/viewtopic.php?f=30&t=113264&hilit=quick+search+all+terms&view=unread#unread

**Comment by Reddiepoint** [comment]
You can do this with my version of the advanced search bar (Search: This thread, By: Author name) + you can also specify search terms to narrow down the messages (e.g. if you are looking for a post containing a release by a certain author you can include the relevant keywords in the search bar in addition to specifying the author)
