### ISSUE TITLE
Theme change problem .

### ISSUE THREAD

**Issue by DogancanYr** [SubZeroPL/cs-rin-ru-enhanced-mod#52]
Can't this piece be made white or in a light color with the numbers inside ?

![image](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/90002969/985741a8-f57b-4cb3-8690-f95e740dba81)

**Comment by Reddiepoint** [comment]
We can add that.

**Comment by DogancanYr** [comment]
I didn't pay attention to the codes.

**Comment by DogancanYr** [comment]
Thanks .

**Comment by DogancanYr** [comment]
Can you increase the brightness of the numbers too?

**Comment by Altansar69** [comment]
@DogancanYr What do you mean ? These number ?
![image](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/97360807/aa07627d-9db4-4e69-8fa2-9bc62947cf62)
I think they're quite visible. They even have a very good contrast ratio.
In what sense did you mean to make them brighter?
Because I honestly can't think of anything.

**Comment by DogancanYr** [comment]
I wish they were more prominent because my screen is big so it's hard to see.

**Comment by Altansar69** [comment]
ohh, you speak about the size ?

**Comment by Altansar69** [comment]
We can probably do that.
and it's true that when we have a big screen, it can be a little hard to see them.

**Comment by DogancanYr** [comment]
So this works for me too.

**Comment by DogancanYr** [comment]
That would be good, thank you once again.

**Comment by Altansar69** [comment]
@DogancanYr done ✔️ 
If you find that it's not enough, you can change the size by modifying the script and changing the size on this line:
    styleElement.textContent = "[name="page_nav\"] {font-size: 1.3em;}" //Increase size of the nav bar
