### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Altansar69** [SubZeroPL/cs-rin-ru-enhanced-mod#54]
![image](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/97360807/1644a3a6-af29-423a-9b6f-630f4a1f6388)
what is all the fie ? @SubZeroPL

**Comment by SubZeroPL** [comment]
Most are for code quality/consistency/form so the code from all developers looks/feels the same
.editorconfig - configuration for editors https://editorconfig.org
.eslintrc.js - linter configuration https://eslint.org/
.gitignore - that one should be obvious
package.json - development libraries
workspace.code-workspace - workspace configuration for Visual Studio Code

**Comment by Altansar69** [comment]
Okay, thanks for the answer. 
I really need to start using an IDE for javascript 😆

**Comment by Altansar69** [comment]
![image](https://github.com/SubZeroPL/cs-rin-ru-enhanced-mod/assets/97360807/37bcd92e-fc96-4cba-b00e-1cc6dd3c6e78)
if I want to create a js project with Visual Studio 2022, I have to choose between Node.js and Vue.js. Which should I choose?

**Comment by Altansar69** [comment]
.editorconfig file, sounds very good i go use it for C++ i think now. Thank you for introducing me to it

**Comment by SubZeroPL** [comment]
> ![image](https://private-user-images.githubusercontent.com/97360807/294657628-37bcd92e-fc96-4cba-b00e-1cc6dd3c6e78.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ2OTk3ODgsIm5iZiI6MTcwNDY5OTQ4OCwicGF0aCI6Ii85NzM2MDgwNy8yOTQ2NTc2MjgtMzdiY2Q5MmUtZmM5Ni00Y2JhLWIwMGUtMWNjNmRkM2M2ZTc4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA4VDA3MzgwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlMzZhNWI4YjY0MzA4ZGVkNzE0MzJlZWE4MTc2OTk3NzVmNmU3MGRiYWVmZDQzMTFiOGMyZGQyMDRmZjhlMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mc0vrn8gniOp0nJCdsxf55hpgEM79CxKOpdsq_qtk1I) if I want to create a js project with Visual Studio 2022, I have to choose between Node.js and Vue.js. Which should I choose?

I don't think Visual Studio is the best IDE for Javascript. Node.js is server-side so not really for us and Vue.js is a framework for web applications so also not really for us (you will have a lot of extra things added that are not needed).
There are lots of different IDEs for web but for such a small project IMHO Visual Studio Code is sufficient (that's what I'm using). You do need to get used to it as it does some things differently that 'standard' Visual Studio but at least (I think) you can change key mappings so they are similar to VS2022.

**Comment by SubZeroPL** [comment]
They should work fine with Jetbrains products (I'm using them - WebStorm, PhpStorm, Rider - myself sometimes)
