### ISSUE TITLE
Navigation bar size .

### ISSUE THREAD

**Issue by DogancanYr** [SubZeroPL/cs-rin-ru-enhanced-mod#56]
I cannot increase the size of the navigation bar. I tried to do it as in the example, but I didn't know how to do it because the code had changed.

**Comment by Altansar69** [comment]
Yes, it's true that things have changed a lot. I'll try to make something more accessible directly in the options for the next update.
Actually it's at line 56: const navBarSize = "1.0em";
change the 1.0 with the size you want. Personally i use 1.2em.

**Comment by DogancanYr** [comment]
I didn't know you simplified the value part, I should have looked more carefully.
❤️❤️
Of course, it would be better if it comes to the settings section.
