### ISSUE TITLE
Reply button with infinite scrolls

### ISSUE THREAD

**Issue by Altansar69** [SubZeroPL/cs-rin-ru-enhanced-mod#67]
It seems that the button to reply to the topic has disappeared again with infinite scroll

**Comment by SubZeroPL** [comment]
For sure it was at the top. AFAIR there were plans to add it to bottom but I don't remember if it was implemented in the end.

**Comment by Altansar69** [comment]
https://i.ibb.co/pL44fL2/image.png He exist before ! xD
