### ISSUE TITLE
Add option to automatically jump to the latest post (+since last visit?)

### ISSUE THREAD

**Issue by sjain882** [SubZeroPL/cs-rin-ru-enhanced-mod#68]
Hi - thanks for this great userscript.

While the infinite scrolling is well made, it's often useful to direct others to page numbers if they are looking for a specific thing. Infinite scrolling makes it ambiguous which page number a post is on, so I don't use the feature.

It would be great if one could store ID of last post someone scrolled over in a thread, and then next time the thread is opened, jump to that post instead. It would be quite useful because I visit the same large threads many times, rather than generally browsing the forum for multiple different threads.

I understand that might be a complex feature to implement, so even something like automatically jumping to the latest page/post would be quite useful - rather than having to click it each time you visit the thread (because I access the threads via bookmarks). You'd only have to go back a page or two then.

**Comment by sjain882** [comment]
Thanks for the info. Unfortunately, since I started using this script, even when I set the topic title option to Unread, it just stays on page 1, reloading the page. An automatic method would be nice, so that it's one less click from the bookmark bar.

**Comment by Altansar69** [comment]
I didn't understand at all what you wanted to do.

**Comment by sjain882** [comment]
> When you set it to "Unread" you should see `&view=unread#unread` in the URL, which is the same as clicking the "First unread post" button. If you want an "automatic method" from the bookmark bar you can just bookmark the topic with `&view=unread#unread` added onto the end.
> 
> Which topic is giving you problems with the unread redirect?

Hi, this was exactly what I was looking for, I forgot about that one. Apologies for the confusion!
