### ISSUE TITLE
Same thing as @KaladinDMP 

### ISSUE THREAD

**Issue by CptAnonymou5** [SubZeroPL/cs-rin-ru-enhanced-mod#72]
@KaladinDMP stated the issue better than I can atm. Using Tampermonkey w/ Thorium/Edge.

2nd issue.
When trying to use search on main CSrin page. After typing search subject, then clicking search nothing happens. If more info is needed or Screenshot's / Vid Clip.

**Comment by KaladinDMP** [comment]
#63

**Comment by Altansar69** [comment]
Sorry, it's still strange but we can't get the bug either. So it's very difficult to fix it without knowing where it comes from.
